### ISSUE TITLE
Can't use DDNS hostname as IP

### ISSUE THREAD

**Issue by JuanMM94** [kwmx/ZomboidRCON#3]
IP field currently allows only IP format inputs. There's no way of configuring a DDNS [example.dnsprovider.org] and I suspect is due to a mere field format check. Shouldn't it work if I just input a DDNS on the IP field?

Thanks.

**Comment by kwmx** [comment]
Hello, I know this sort of a late reply but as I plan on updating the software I decided to look over all issues before starting. I don't believe it's possible to work around a DDNS on the current design as the address of a server is used to create the database and keep the data separate for different server connections. I'll try to look into it but tbh it won't be a high priority in the current time. If you want to experiment with it and find a solution that would work without effecting the features of the program I would be happy to apply your changes.

**Comment by JuanMM94** [comment]
Thanks for the reply, even if it's a "late" one. I know little about coding but I'll give it a try at least. Anyways, amazing little app you've done! I use it quite a lot if I'm being honest. So thanks for that!

**Comment by mizifih** [comment]
> I don't believe it's possible to work around a DDNS on the current design as the address of a server is used to create the database and keep the data separate for different server connections.

So what happens for people running servers with dynamic IPs? Like, ok, locally I wont have a problem, since my server has a fixed local IP, but I mostly access my server remotely. It's not that hard to access it using your tool (thanks for it, btw), all I had to do was ping the domain name and use the IP that responded, but what about the database? The remote IP will inevitably change, It'll reset the database and consider it a different server?

**Comment by kwmx** [comment]
Pushed an update (v1.0.4) that should fix and support this with a persistent database. 

Please report any issues that arise.
